import ExcelJS from "exceljs";
import PDFDocument from "pdfkit";
import type { DatasetDefinition, ExportColumn } from "./export.service";

/**
 * Turns any dataset into CSV, Excel or PDF.
 *
 * Format writers live here rather than beside the queries so that adding an
 * export means describing its columns once (`DATASETS` in `export.service.ts`)
 * and getting all three formats for free.
 *
 * All three return a Buffer rather than streaming. Exports are capped at 10,000
 * rows, which is a few megabytes at worst, and buffering means a query failure
 * produces a clean JSON error instead of a half-written file the browser has
 * already started saving.
 */

export interface RenderInput {
  definition: DatasetDefinition;
  rows: Record<string, unknown>[];
  from?: string;
  to?: string;
  generatedBy: string;
}

// ------------------------------------------------------------------ CSV

/**
 * RFC 4180 quoting, plus one thing that is not in the RFC.
 *
 * A value beginning with `=`, `+`, `-` or `@` is executed as a formula when the
 * file is opened in Excel or Sheets. Guest names and review comments are
 * attacker-controlled text, so each of those is prefixed with a tab — the value
 * still reads correctly, but the spreadsheet treats it as text. Without this,
 * a review saying `=HYPERLINK(...)` becomes a live link in the owner's export.
 */
function csvCell(value: unknown): string {
  if (value === null || value === undefined) return "";
  let str = String(value);

  if (/^[=+\-@\t\r]/.test(str)) str = `\t${str}`;

  if (/[",\n\r]/.test(str)) {
    return `"${str.replace(/"/g, '""')}"`;
  }
  return str;
}

export function renderCsv({ definition, rows }: RenderInput): Buffer {
  const header = definition.columns.map((c) => csvCell(c.header)).join(",");
  const body = rows.map((row) =>
    definition.columns.map((c) => csvCell(row[c.key])).join(",")
  );

  // A BOM so Excel opens UTF-8 correctly — without it, "₹" and accented names
  // arrive as mojibake on a default Windows install.
  return Buffer.from(`﻿${[header, ...body].join("\r\n")}\r\n`, "utf8");
}

// ---------------------------------------------------------------- Excel

export async function renderXlsx({
  definition,
  rows,
  from,
  to,
  generatedBy,
}: RenderInput): Promise<Buffer> {
  const workbook = new ExcelJS.Workbook();
  workbook.creator = "7 Vachan";
  workbook.created = new Date();

  const sheet = workbook.addWorksheet(definition.label.slice(0, 31));

  sheet.columns = definition.columns.map((c) => ({
    header: c.header,
    key: c.key,
    width: c.width ?? 18,
  }));

  rows.forEach((row) => sheet.addRow(row));

  const headerRow = sheet.getRow(1);
  headerRow.font = { bold: true, color: { argb: "FFFFFFFF" } };
  headerRow.fill = { type: "pattern", pattern: "solid", fgColor: { argb: "FF4F46E5" } };
  headerRow.alignment = { vertical: "middle" };
  headerRow.height = 20;

  definition.columns.forEach((c, index) => {
    if (c.numeric) {
      sheet.getColumn(index + 1).alignment = { horizontal: "right" };
      sheet.getColumn(index + 1).numFmt = "#,##0.##";
    }
  });

  // Freeze the header and turn on autofilter — the two things anyone does
  // manually within five seconds of opening a report like this.
  sheet.views = [{ state: "frozen", ySplit: 1 }];
  sheet.autoFilter = {
    from: { row: 1, column: 1 },
    to: { row: 1, column: definition.columns.length },
  };

  addTotalsRow(sheet, definition, rows);

  const meta = workbook.addWorksheet("About");
  meta.columns = [{ width: 22 }, { width: 60 }];
  meta.addRows([
    ["Report", definition.label],
    ["Description", definition.description],
    ["Date range", describeRange(from, to)],
    ["Rows", rows.length],
    ["Generated", new Date().toISOString().slice(0, 16).replace("T", " ")],
    ["Generated by", generatedBy],
  ]);
  meta.getColumn(1).font = { bold: true };

  const buffer = await workbook.xlsx.writeBuffer();
  return Buffer.from(buffer);
}

/** A bold sum under every numeric column, skipping counts that make no sense to add. */
function addTotalsRow(
  sheet: ExcelJS.Worksheet,
  definition: DatasetDefinition,
  rows: Record<string, unknown>[]
) {
  const numericColumns = definition.columns.filter((c) => c.numeric);
  if (numericColumns.length === 0 || rows.length === 0) return;

  const totals: Record<string, unknown> = {};
  totals[definition.columns[0].key] = "Total";

  for (const column of numericColumns) {
    totals[column.key] = rows.reduce((sum, row) => sum + toNumber(row[column.key]), 0);
  }

  const row = sheet.addRow(totals);
  row.font = { bold: true };
  row.border = { top: { style: "thin" } };
}

// ------------------------------------------------------------------ PDF

/**
 * A landscape table.
 *
 * PDF is offered only for datasets whose columns fit a page; `DATASETS` decides
 * which those are (Customers, for instance, is CSV/Excel only). Columns are
 * laid out proportionally to their declared widths so a 60-character comment
 * column gets the room it needs and an 8-character rating column does not.
 */
export function renderPdf({ definition, rows, from, to, generatedBy }: RenderInput): Promise<Buffer> {
  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({ size: "A4", layout: "landscape", margin: 36 });
    const chunks: Buffer[] = [];

    doc.on("data", (chunk: Buffer) => chunks.push(chunk));
    doc.on("end", () => resolve(Buffer.concat(chunks)));
    doc.on("error", reject);

    const pageWidth = doc.page.width - doc.page.margins.left - doc.page.margins.right;
    const totalWeight = definition.columns.reduce((sum, c) => sum + (c.width ?? 18), 0);
    const widths = definition.columns.map((c) => ((c.width ?? 18) / totalWeight) * pageWidth);

    doc.fontSize(16).fillColor("#141210").text("7 Vachan", { continued: true });
    doc.fontSize(16).fillColor("#4F46E5").text(`  ·  ${definition.label}`);
    doc.moveDown(0.3);
    doc
      .fontSize(8)
      .fillColor("#6B7280")
      .text(
        `${describeRange(from, to)}  ·  ${rows.length} row${rows.length === 1 ? "" : "s"}  ·  generated ${new Date()
          .toISOString()
          .slice(0, 16)
          .replace("T", " ")} by ${generatedBy}`
      );
    doc.moveDown(0.8);

    let y = doc.y;

    const drawHeader = () => {
      doc.rect(doc.page.margins.left, y - 3, pageWidth, 16).fill("#4F46E5");
      let x = doc.page.margins.left;
      doc.fontSize(7.5).fillColor("#FFFFFF");
      definition.columns.forEach((column, index) => {
        doc.text(column.header, x + 3, y, {
          width: widths[index] - 6,
          align: column.numeric ? "right" : "left",
          lineBreak: false,
        });
        x += widths[index];
      });
      y += 16;
      doc.fillColor("#141210");
    };

    drawHeader();

    doc.fontSize(7.5);
    rows.forEach((row, rowIndex) => {
      // Page breaks re-draw the header, otherwise page 2 onwards is unreadable.
      if (y > doc.page.height - doc.page.margins.bottom - 24) {
        doc.addPage();
        y = doc.page.margins.top;
        drawHeader();
        doc.fontSize(7.5);
      }

      if (rowIndex % 2 === 1) {
        doc.rect(doc.page.margins.left, y - 2, pageWidth, 13).fill("#F5F5F4");
        doc.fillColor("#141210");
      }

      let x = doc.page.margins.left;
      definition.columns.forEach((column, index) => {
        const raw = row[column.key];
        const text = raw === null || raw === undefined ? "" : String(raw);
        doc.fillColor("#141210").text(truncateToWidth(text, widths[index]), x + 3, y, {
          width: widths[index] - 6,
          align: column.numeric ? "right" : "left",
          lineBreak: false,
          ellipsis: true,
        });
        x += widths[index];
      });
      y += 13;
    });

    if (rows.length === 0) {
      doc.moveDown(2).fontSize(10).fillColor("#6B7280").text("No records in this date range.", {
        align: "center",
      });
    }

    doc.end();
  });
}

/** Rough character budget for a column; `ellipsis` handles the exact fit. */
function truncateToWidth(text: string, width: number): string {
  const max = Math.max(4, Math.floor(width / 3.6));
  return text.length > max ? `${text.slice(0, max - 1)}…` : text;
}

// ---------------------------------------------------------------- shared

function toNumber(value: unknown): number {
  const n = Number(value);
  return Number.isFinite(n) ? n : 0;
}

export function describeRange(from?: string, to?: string): string {
  if (from && to) return `${from} to ${to}`;
  if (from) return `from ${from}`;
  if (to) return `up to ${to}`;
  return "all time";
}

export function contentTypeFor(format: string): string {
  switch (format) {
    case "csv":
      return "text/csv; charset=utf-8";
    case "xlsx":
      return "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet";
    case "pdf":
      return "application/pdf";
    default:
      return "application/octet-stream";
  }
}
